### ISSUE TITLE
Deploy read-only instance

### ISSUE THREAD

**Issue by 72636c** [seek-oss/wingman#3]
Per https://github.com/seek-oss/wingman/pull/1#issuecomment-636784627, it would be nice to deploy a read-only instance of Wingman in CI.

Prerequisites:

- Find an unprivileged AWS account to deploy a public GraphQL server into
- Check that all data accessible through Playground credentials can be made fully public

**Comment by AaronMoat** [comment]
https://github.com/seek-oss/wingman/pull/1105
